# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SF4KZZDvhqYE0XIVac079ecqm7BPVrhJ
"""

import pandas as pd
import matplotlib.pyplot as plt
# Load dataset
df = pd.read_csv('powerbi_sales_data.csv')
# Show first rows
print("Sample Data:")
print(df.head())
# Total Sales & Profit
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
print("\nTotal Sales:", total_sales)
print("Total Profit:", total_profit)
# Sales by Region
region_sales = df.groupby('Region')['Sales'].sum()
print("\nSales by Region:\n", region_sales)
# Top Products
top_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(5)
print("\nTop 5 Products:\n", top_products)
# Monthly Trend
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('Month')['Sales'].sum()
# Plot 1: Region Sales
region_sales.plot(kind='bar', title='Sales by Region')
plt.xlabel("Region")
plt.ylabel("Sales")
plt.show()
# Plot 2: Monthly Trend
monthly_sales.plot(kind='line', title='Monthly Sales Trend')
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()